vim.cmd("set tabstop=4")
vim.cmd("set softtabstop=4")
vim.cmd("set shiftwidth=4")
vim.cmd("set number")
vim.cmd("set autoindent")
vim.cmd("set smarttab")
vim.cmd("set mouse=a")
vim.cmd("set encoding=utf8")
vim.cmd("set history=5000")
vim.cmd("set clipboard=unnamedplus")
vim.g.mapleader = " "
